
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false, nfs: {nolock: true}, nfs_export: false
  config.vm.provision "shell", path: "provision.sh"

end
